/**
 * Export the companion-repo scaffold from the curriculum.
 *
 *   npx tsx scripts/export-companion.ts <target-dir>
 *
 * Mirrors the quest map as directories — <section>/<NN-phase-slug>/<quest-id>/ —
 * and writes a generated README.md into each phase and quest directory.
 *
 * Idempotent and safe to re-run after curriculum changes: it only creates
 * directories and overwrites README.md files that carry the GENERATED marker.
 * It never touches any other file, and it refuses to overwrite a README a
 * human has taken over (marker removed).
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { PHASES, QUESTS, phaseLabel } from "../src/data/curriculum";
import type { Quest, Task } from "../src/lib/types";

const MARKER =
  "<!-- generated by inferquest scripts/export-companion.ts — edit curriculum.ts, then re-run -->";

const SITE = "https://inferquest.org";

const target = process.argv[2];
if (!target) {
  console.error("usage: npx tsx scripts/export-companion.ts <target-dir>");
  process.exit(1);
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** section/NN-slug for a phase */
function phaseDir(phaseId: string): string {
  const p = PHASES.find((p) => p.id === phaseId)!;
  return path.join(p.section, `${String(p.number).padStart(2, "0")}-${slug(p.title)}`);
}

function questDir(q: Quest): string {
  return path.join(phaseDir(q.phaseId), q.id);
}

function verifierNote(t: Task): string | null {
  if (!t.verifier) return null;
  switch (t.verifier.type) {
    case "endpoint":
      return "verified by a live endpoint probe";
    case "github-pr":
      return "verified by a merged-PR check";
    case "url":
      return "verified by a published-URL check";
    case "harness":
      return "graded by the local GPU harness";
    case "quiz":
      return "graded quiz on the site";
  }
}

/** Task kinds whose work product normally lives in this repo. */
const REPO_KINDS = new Set(["build", "kernel", "bench", "write"]);

function taskLine(t: Task): string {
  const bits = [`- \`${t.kind}\` **${t.title}** · ${t.xp} XP`];
  const note = verifierNote(t);
  if (note) bits.push(`  — ${note}`);
  if (t.link) bits.push(`  — [resource](${t.link})`);
  return bits.join("");
}

function questReadme(q: Quest): string {
  const phase = PHASES.find((p) => p.id === q.phaseId)!;
  const lines: string[] = [MARKER, ""];
  lines.push(`# ${q.title}`);
  lines.push("");
  lines.push(`${phaseLabel(phase)} — ${phase.title} · [quest page](${SITE}/quests/${q.id})`);
  lines.push("");
  lines.push(`*${q.tagline}*`);
  lines.push("");
  if (q.prereqs.length > 0) {
    const links = q.prereqs.map((id) => {
      const pq = QUESTS.find((x) => x.id === id);
      if (!pq) return `\`${id}\``;
      const rel = path.relative(questDir(q), questDir(pq));
      return `[${pq.title}](${rel}/)`;
    });
    lines.push(`Builds on: ${links.join(" · ")}`);
    lines.push("");
  }
  lines.push("## Tasks");
  lines.push("");
  for (const t of q.tasks) lines.push(taskLine(t));
  lines.push("");
  const repoTasks = q.tasks.filter((t) => REPO_KINDS.has(t.kind));
  if (repoTasks.length > 0) {
    lines.push("## What lives here");
    lines.push("");
    lines.push(
      "Code, benchmarks, and writeups for the tasks above. Name each task's " +
        "work after its id so it's findable from the site — for example " +
        `\`${repoTasks[0].id.replace(/-/g, "_")}.py\` or a \`${repoTasks[0].id}/\` folder. ` +
        "Reading, videos, and quizzes complete on the site; notes on them are " +
        "welcome here but optional.",
    );
  } else {
    lines.push("## What lives here");
    lines.push("");
    lines.push(
      "This quest is reading, videos, or quizzes that complete on the site. " +
        "Use this directory for notes and worked examples if you want a record.",
    );
  }
  lines.push("");
  return lines.join("\n");
}

function phaseReadme(phaseId: string): string {
  const p = PHASES.find((x) => x.id === phaseId)!;
  const quests = QUESTS.filter((q) => q.phaseId === phaseId);
  const lines: string[] = [MARKER, ""];
  lines.push(`# ${phaseLabel(p)}: ${p.title}`);
  lines.push("");
  lines.push(p.description);
  lines.push("");
  lines.push("## Quests");
  lines.push("");
  for (const q of quests) {
    lines.push(`- [${q.title}](${q.id}/) — ${q.tagline}`);
  }
  lines.push("");
  return lines.join("\n");
}

function writeGenerated(file: string, content: string): "written" | "skipped" {
  if (fs.existsSync(file)) {
    const existing = fs.readFileSync(file, "utf8");
    if (!existing.includes(MARKER)) return "skipped";
  }
  fs.writeFileSync(file, content);
  return "written";
}

let written = 0;
let skipped = 0;

for (const p of PHASES) {
  const dir = path.join(target, phaseDir(p.id));
  fs.mkdirSync(dir, { recursive: true });
  const r = writeGenerated(path.join(dir, "README.md"), phaseReadme(p.id));
  r === "written" ? written++ : skipped++;
}

for (const q of QUESTS) {
  const dir = path.join(target, questDir(q));
  fs.mkdirSync(dir, { recursive: true });
  const r = writeGenerated(path.join(dir, "README.md"), questReadme(q));
  r === "written" ? written++ : skipped++;
}

console.log(
  `companion scaffold: ${PHASES.length} phases, ${QUESTS.length} quests → ${target}`,
);
console.log(`READMEs written: ${written}, left alone (human-owned): ${skipped}`);
